package com.yelloco.payment.utils;

public enum DisplayMessageEnum {

    AMOUNT(0xCB01, "AMOUNT_AUTHORISED", "MONTANT"),
    AMOUNT_OK(0xCB02, "AMOUNT_AUTHORISED OK?", "MONTANT OK?"),
    APPROVED(0xCB03, "APPROVED", "PAIEMENT ACCEPTE"),
    CALL_YOUR_BANK(0xCB04, "CALL YOUR BANK", "APPELER BANQUE"),
    CANCEL_OR_ENTER(0xCB05, "CANCEL OR ENTER", "ABANDONNER OU VALIDER"),
    CARD_ERROR(0xCB06, "CARD ERROR", "ERREUR CARTE"),
    DECLINED(0xCB07, "DECLINED", "PAIEMENT REFUSE"),
    ENTER_AMOUNT(0xCB08, "ENTER AMOUNT_AUTHORISED", "ENTREZ MONTANT"),
    ENTER_PIN(0xCB09, "ENTER PIN", "CODE ?"),
    INCORRECT_PIN(0xCB0A, "INCORRECT PIN", "CODE FAUX"),
    INSERT_CARD(0xCB0B, "INSERT CARD", "INSEREZ CARTE"),
    NOT_ACCEPTED(0xCB0C, "NOT ACCEPTED", "CARTE REFUSEE"),
    PIN_OK(0xCB0D, "PIN OK", "CODE BON"),
    PLEASE_WAIT(0xCB0E, "PLEASE WAIT", "PATIENTEZ"),
    PROCESSING_ERROR(0xCB0F, "PROCESSING ERROR", "INCIDENT TECHNIQUE"),
    REMOVE_CARD(0xCB10, "REMOVE CARD", "RETIREZ CARTE"),
    USE_CHIP_READER(0xCB11, "USE CHIP READER", "UTILISEZ PUCE"),
    USE_MAG_STRIPE(0xCB12, "USE MAG STRIPE", "UTILISEZ PISTE MAGNETIQUE"),
    TRY_AGAIN(0xCB13, "TRY AGAIN", "NOUVEL ESSAI"),
    WELCOME(0xCB14, "WELCOME", "BIENVENUE"),
    PRESENT_CARD(0xCB15, "PRESENT CARD", "PRESENTEZ CARTE"),
    PROCESSING(0xCB16, "PROCESSING", "TRAITEMENT"),
    CARD_READ_OK_REMOVE_CARD(0xCB17, "CARD READ OK, REMOVE CARD", "ENLEVEZ LA CARTE"),
    INSERT_OR_SWIPE(0xCB18, "INSERT OR SWIPE", "PUCE OU PISTE MAGNETIQUE"),
    PRESENT_ONE_CARD_ONLY(0xCB19, "PRESENT ONE CARD ONLY", "PRESENTEZ UNE SEULE CARTE"),
    APPROVED_PLEASE_SIGN(0xCB1A, "APPROVED, PLEASE SIGN", "SIGNATURE"),
    AUTHORIZING_PLEASE_WAIT(0xCB1B, "AUTHORIZING, PLEASE WAIT", "AUTORISATION EN COURS"),
    INSERT_SWIPE_OR_TRY_ANOTHER_CARD(0xCB1C, "INSERT, SWIPE OR TRY ANOTHER CARD", "UTILISEZ UNE AUTRE CARTE"),
    PLEASE_INSERT_CARD(0xCB1D, "PLEASE INSERT CARD", "INSEREZ CARTE"),
    SEE_PHONE_FOR_INSTRUCTIONS(0xCB20, "SEE PHONE FOR INSTRUCTIONS", "REGARDEZ VOTRE MOBILE"),
    PRESENT_CARD_AGAIN(0xCB21, "PRESENT CARD AGAIN", "PRESENTEZ CARTE ENCORE"),
    LAST_PIN_TRY(0xCB22, "LAST PIN TRY", "DERNIER ESSAI");

    public final int code;
    public final String english;
    public final String french;

    DisplayMessageEnum(int code, String english, String french) {
        this.code = code;
        this.english = english;
        this.french = french;
    }
}
